module.exports = [
  {
    name: 'The Pretender',
    album_id: 1,
    artist_id: 1,
    length: '04:30:00',
    track_number: null,
    lyrics: 'to be added',
    youtube_link: 'SBjQ9tuuTJQ',
  },
  {
    name: 'All My Life',
    album_id: 1,
    artist_id: 1,
    length: '04:44:00',
    track_number: null,
    lyrics: 'to be added',
    youtube_link: 'xQ04WbgI9rg',
  },
  {
    name: 'Everlong',
    album_id: 1,
    artist_id: 1,
    length: '04:49:00',
    track_number: null,
    lyrics: 'to be added',
    youtube_link: 'eBG7P-K-r1Y',
  },
  {
    name: 'Cant Stop',
    album_id: 2,
    artist_id: 2,
    length: '04:37:00',
    track_number: null,
    lyrics: 'to be added',
    youtube_link: '8DyziWtkfBw',
  },
  {
    name: 'By The Way',
    album_id: 2,
    artist_id: 2,
    length: '03:37:00',
    track_number: null,
    lyrics: 'to be added',
    youtube_link: 'JnfyjwChuNU',
  },
  {
    name: 'This Is The Place',
    album_id: 2,
    artist_id: 2,
    length: '04:30:00',
    track_number: null,
    lyrics: 'to be added',
    youtube_link: 'gqgm7ViA2Ag',
  },
  {
    name: 'Never Mine',
    album_id: 3,
    artist_id: 3,
    length: '03:45:00',
    track_number: null,
    lyrics: 'to be added',
    youtube_link: 'zk3bQ3CJNg4',
  },
  {
    name: 'Coffee Stains',
    album_id: 3,
    artist_id: 3,
    length: '03:14:00',
    track_number: null,
    lyrics: 'to be added',
    youtube_link: '5kDr5863BoI',
  },
  {
    name: 'Oh Sister',
    album_id: 3,
    artist_id: 3,
    length: '03:30:00',
    track_number: null,
    lyrics: 'to be added',
    youtube_link: 'YSg9qE-oDGU',
  },
  {
    name: 'Misguided Ghosts',
    album_id: 4,
    artist_id: 4,
    length: '02:58:00',
    track_number: null,
    lyrics: 'to be added',
    youtube_link: 'oGWeHPK3NC4',
  },
  {
    name: 'All I Wanted',
    album_id: 4,
    artist_id: 4,
    length: '03:45:00',
    track_number: null,
    lyrics: 'to be added',
    youtube_link: 'W7nmB20qJv4',
  },
  {
    name: 'Where The Lines Overlap',
    album_id: 4,
    artist_id: 4,
    length: '03:16:00',
    track_number: null,
    lyrics: 'to be added',
    youtube_link: 'blDjUkMA9oU',
  },
  {
    name: 'myboy',
    album_id: 5,
    artist_id: 5,
    length: '02:50:00',
    track_number: null,
    lyrics: 'to be added',
    youtube_link: 'dVUmSgzgOqs',
  },
  {
    name: 'party favor',
    album_id: 5,
    artist_id: 5,
    length: '03:23:00',
    track_number: null,
    lyrics: 'to be added',
    youtube_link: 'tGHTOVw6F4Q',
  },
  {
    name: 'idontwannabeyouanymore',
    album_id: 5,
    artist_id: 5,
    length: '03:24:00',
    track_number: null,
    lyrics: 'to be added',
    youtube_link: '-tn2S3kJlyU',
  },
  {
    name: 'Come As You Are',
    album_id: 6,
    artist_id: 6,
    length: '03:45:00',
    track_number: null,
    lyrics: 'to be added',
    youtube_link: 'vabnZ9-ex7o',
  },
  {
    name: 'Smells Like Teen Spirit',
    album_id: 6,
    artist_id: 6,
    length: '04:38:00',
    track_number: null,
    lyrics: 'to be added',
    youtube_link: 'hTWKbfoikeg',
  },
  {
    name: 'Lithium',
    album_id: 6,
    artist_id: 6,
    length: '04:17:00',
    track_number: null,
    lyrics: 'to be added',
    youtube_link: 'LYfnBsaTVEo',
  },
  {
    name: 'Tribute',
    album_id: 7,
    artist_id: 7,
    length: '04:52:00',
    track_number: null,
    lyrics: 'to be added',
    youtube_link: '_lK4cX5xGiQ',
  },
  {
    name: 'Wonderboy',
    album_id: 7,
    artist_id: 7,
    length: '04:31:00',
    track_number: null,
    lyrics: 'to be added',
    youtube_link: 'FL4HSiGvk68',
  },
  {
    name: 'Kielbasa',
    album_id: 7,
    artist_id: 7,
    length: '03:00:00',
    track_number: null,
    lyrics: 'to be added',
    youtube_link: '7LBxr5ZScqE',
  },
  {
    name: 'Dear God',
    album_id: 8,
    artist_id: 8,
    length: '04:42:00',
    track_number: null,
    lyrics: 'to be added',
    youtube_link: 'mzX0rhF8buo',
  },
  {
    name: 'So Far Away',
    album_id: 11,
    artist_id: 8,
    length: '05:28:00',
    track_number: null,
    lyrics: 'to be added',
    youtube_link: 'A7ry4cx6HfY',
  },
  {
    name: 'Buried Alive',
    album_id: 11,
    artist_id: 8,
    length: '06:47:00',
    track_number: null,
    lyrics: 'to be added',
    youtube_link: 'imwmmv9r1oE',
  },
  {
    name: 'Gunslinger',
    album_id: 8,
    artist_id: 8,
    length: '04:11:00',
    track_number: null,
    lyrics: 'to be added',
    youtube_link: '3vDetD8cW_o',
  },
  {
    name: 'Space Bound',
    album_id: 9,
    artist_id: 9,
    length: '04:24:00',
    track_number: null,
    lyrics: 'to be added',
    youtube_link: 'JByDbPn6A1o',
  },
  {
    name: 'Love The Way You Lie',
    album_id: 9,
    artist_id: 9,
    length: '04:26:00',
    track_number: null,
    lyrics: 'to be added',
    youtube_link: 'uelHwf8o7_U',
  },
  {
    name: 'Not Afraid',
    album_id: 9,
    artist_id: 9,
    length: '04:18:00',
    track_number: null,
    lyrics: 'to be added',
    youtube_link: 'j5-yKhDd64s',
  },
  {
    name: 'Evil Angel',
    album_id: 10,
    artist_id: 10,
    length: '03:40:00',
    track_number: null,
    lyrics: 'to be added',
    youtube_link: 'Wjrh8vid0IE',
  },
  {
    name: 'Unknown Soldier',
    album_id: 10,
    artist_id: 10,
    length: '03:42:00',
    track_number: null,
    lyrics: 'to be added',
    youtube_link: 'SQl3waLGR4s',
  },
  {
    name: 'The Diary Of Jane',
    album_id: 10,
    artist_id: 10,
    length: '03:27:00',
    track_number: null,
    lyrics: 'to be added',
    youtube_link: 'DWaB4PXCwFU',
  },
  {
    name: 'Breath',
    album_id: 10,
    artist_id: 10,
    length: '03:38:00',
    track_number: null,
    lyrics: 'to be added',
    youtube_link: 'Ib9swdvt3mA',
  },
  {
    name: 'Bad Guy',
    album_id: 5,
    artist_id: 5,
    length: '00:03:26',
    track_number: null,
    lyrics: 'soon...',
    youtube_link: 'DyDfgMOUjCI',
  },
  {
    name: 'What do you mean?',
    album_id: 27,
    artist_id: 26,
    length: '04:57:00',
    track_number: null,
    lyrics: 'What do you mean?',
    youtube_link: 'DK_0jXPuIr0',
  },
];
