module.exports = [
  { user_id: 2, playlist_id: 3 },
  { user_id: 3, playlist_id: 2 },
  { user_id: 6, playlist_id: 1 },
  { user_id: 14, playlist_id: 1 },
  { user_id: 10, playlist_id: 1 },
  { user_id: 26, playlist_id: 2 },
  { user_id: 3, playlist_id: 1 },
  { user_id: 21, playlist_id: 1 },
  { user_id: 3, playlist_id: 2 },
  { user_id: 27, playlist_id: 3 },
  { user_id: 9, playlist_id: 1 },
  { user_id: 30, playlist_id: 1 },
  { user_id: 26, playlist_id: 1 },
  { user_id: 15, playlist_id: 1 },
  { user_id: 29, playlist_id: 3 },
  { user_id: 23, playlist_id: 3 },
  { user_id: 28, playlist_id: 3 },
  { user_id: 24, playlist_id: 3 },
  { user_id: 8, playlist_id: 3 },
  { user_id: 29, playlist_id: 2 },
  { user_id: 9, playlist_id: 3 },
  { user_id: 30, playlist_id: 3 },
  { user_id: 16, playlist_id: 3 },
  { user_id: 20, playlist_id: 3 },
  { user_id: 24, playlist_id: 2 },
  { user_id: 6, playlist_id: 3 },
  { user_id: 2, playlist_id: 2 },
  { user_id: 8, playlist_id: 3 },
  { user_id: 15, playlist_id: 1 },
  { user_id: 4, playlist_id: 2 },
  { user_id: 6, playlist_id: 2 },
  { user_id: 17, playlist_id: 2 },
  { user_id: 22, playlist_id: 2 },
  { user_id: 17, playlist_id: 3 },
  { user_id: 6, playlist_id: 3 },
  { user_id: 23, playlist_id: 2 },
  { user_id: 4, playlist_id: 2 },
  { user_id: 6, playlist_id: 2 },
  { user_id: 18, playlist_id: 2 },
  { user_id: 22, playlist_id: 2 },
  { user_id: 14, playlist_id: 1 },
  { user_id: 28, playlist_id: 3 },
  { user_id: 13, playlist_id: 3 },
  { user_id: 14, playlist_id: 2 },
  { user_id: 13, playlist_id: 2 },
  { user_id: 12, playlist_id: 2 },
  { user_id: 3, playlist_id: 1 },
  { user_id: 29, playlist_id: 2 },
  { user_id: 13, playlist_id: 2 },
  { user_id: 28, playlist_id: 1 },
  { user_id: 5, playlist_id: 2 },
  { user_id: 25, playlist_id: 2 },
  { user_id: 24, playlist_id: 3 },
  { user_id: 21, playlist_id: 2 },
  { user_id: 16, playlist_id: 1 },
  { user_id: 9, playlist_id: 3 },
  { user_id: 24, playlist_id: 3 },
  { user_id: 20, playlist_id: 1 },
  { user_id: 19, playlist_id: 3 },
  { user_id: 19, playlist_id: 1 },
  {
    user_id: 1,
    playlist_id: 1,
.000Z',
    updated_at: '2020-10-01T13:08:40.000Z',
  },
];
