POST http://localhost:3001/api/artists
Content-Type: application/json

{
    "collums": ["name", "cover_img"],
    "values" : ["Khalid", "https://thetrinityvoice.com/wp-content/uploads/2018/03/Screen-Shot-2018-03-15-at-2.28.14-PM.png"]
}