POST http://localhost:3001/api/albums
Content-Type: application/json

{
    "collums": ["name", "cover_img", "artist_id", "created_at"],
    "values" : ["Free Spirit", "SoonToBeAdded", 22, "2019-04-05" ]
}