POST http://localhost:3001/api/songs
Content-Type: application/json

{
    "collums" : ["name",  "artist_id", "album_id", "lyrics", "youtube_link"],
    "values" : ["shishlik", 2, 2, "harta", "barta"]
}